// data.js
import { krish, krishna, brickNoBg, allGoldNoBg, fatBottleNoBg, longBottleNoBg, twoBlackGoldNoBg, sliderBottleOneNoBg, sliderBottleTwoNoBg, sliderBottleThreeNoBg, sliderBottleFourNoBg, blackBigNoBg, blackGoldNoBg, } from "@/exports/image-exports";
export const perfumeData = [
    {
      id: 1,
      name: "Velvet Orchid",
      price: "$120",
      image: brickNoBg,
      gender: 'female',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'A refreshing mix of lavender, eucalyptus, and cedarwood, offering a tranquil escape into nature’s embrace. Perfect for a calm, confident presence.',
    },
    {
      id: 2,
      name: "Black Opium",
      price: "$95",
      image: allGoldNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'oud',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Embark on a journey with bold cinnamon, fiery cloves, and warm vanilla. A daring fragrance for the adventurous soul.',
    },
    {
      id: 3,
      name: "Sauvage",
      price: "$150",
      image: fatBottleNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'A sophisticated aroma of fresh roses, pink pepper, and creamy sandalwood. Romantic yet modern, it’s love at first spritz.',
    },
    {
      id: 4,
      name: "Flowerbomb",
      price: "$110",
      image: longBottleNoBg,
      gender: 'female',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'A rich blend of amber, patchouli, and smoky tonka bean. Mysterious and alluring, this scent is made for those who own the night.',
    },
    {
      id: 5,
      name: "Light Blue",
      price: "$85",
      image: twoBlackGoldNoBg,
      gender: 'female',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'An exquisite bouquet of peony, magnolia, and lily-of-the-valley, enveloped in a light, musky base. Feminine, fresh, and irresistibly graceful.',
    },
    {
      id: 6,
      name: "Good Girl",
      price: "$105",
      image: blackBigNoBg,
      gender: 'female',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Energize your senses with the vibrant notes of Sicilian lemon, juicy mandarin, and crisp green tea. Perfect for sunny days and spirited adventures.',
    },
    {
      id: 7,
      name: "Creed Williams",
      price: "$15.99",
      image: sliderBottleOneNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Dive into the freshness of sea breeze, zesty bergamot, and calming driftwood. A fragrance that feels like a serene day by the coast',
    },
    {
      id: 8,
      name: "Davis Taylor",
      price: "$39.66",
      image: sliderBottleTwoNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Indulge in the allure of black orchid, spiced sandalwood, and smoky vetiver. A bold statement for the modern mystique.',
    },
    {
      id: 9,
      name: "Elyse Creek",
      price: "$20.35",
      image: sliderBottleThreeNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'oud',
      container: 'glass bottle',
      state: 'liquid',
      description: "A captivating blend of blooming jasmine and sweet vanilla, accented with a whisper of amber to leave an unforgettable impression. Perfect for those who dream in color",
    },
    {
      id: 10,
      name: "Black Orchid",
      price: "$25.69",
      image: sliderBottleFourNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'oud',
      container: 'glass bottle',
      state: 'liquid',
       description: "An opulent scent combining warm honey, golden musk, and a touch of white oud for a fragrance that glows as brilliantly as its name.",
    },
    {
      id: 11,
      name: "Marc Jacobs Daisy",
      price: "$10.99",
      image: blackGoldNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'Glass bottle',
      state: 'liquid',
      description: "By marc jacobs for men",
    },
  ];
  
  const mostRecent = [
    {
      id: 11,
      name: "Marc Jacobs Daisy",
      price: "$10.99",
      image: blackGoldNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'Glass bottle',
      state: 'liquid',
      description: "By marc jacobs for men",
    },
  ]

  const recentFour = [
    {
      id: 7,
      name: "Creed Williams",
      price: "$15.99",
      image: sliderBottleOneNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Dive into the freshness of sea breeze, zesty bergamot, and calming driftwood. A fragrance that feels like a serene day by the coast',
    },
    {
      id: 8,
      name: "Davis Taylor",
      price: "$39.66",
      image: sliderBottleTwoNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'wood',
      container: 'glass bottle',
      state: 'liquid',
      description: 'Indulge in the allure of black orchid, spiced sandalwood, and smoky vetiver. A bold statement for the modern mystique.',
    },
    {
      id: 9,
      name: "Elyse Creek",
      price: "$20.35",
      image: sliderBottleThreeNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'oud',
      container: 'glass bottle',
      state: 'liquid',
      description: "A captivating blend of blooming jasmine and sweet vanilla, accented with a whisper of amber to leave an unforgettable impression. Perfect for those who dream in color",
    },
    {
      id: 10,
      name: "Black Orchid",
      price: "$25.69",
      image: sliderBottleFourNoBg,
      gender: 'male',
      form: 'spray',
      capacity: '100ml',
      scent: 'oud',
      container: 'glass bottle',
      state: 'liquid',
       description: "An opulent scent combining warm honey, golden musk, and a touch of white oud for a fragrance that glows as brilliantly as its name.",
    },
  ]

  export {
    mostRecent,
    recentFour,
  }